[package]
name = "rocket-app"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.39", features = ["serde"] }


